package com.auction.network;

public enum CommandType {
    LOGIN, REGISTER,
    CANCEL_AUCTION,
    GET_AUCTIONS, GET_AUCTION_DETAIL, GET_MY_BIDS,
    GET_WON_AUCTIONS,
    CREATE_AUCTION, PLACE_BID,
    REGISTER_AUTO_BID, CANCEL_AUTO_BID,
    CLOSE_AUCTION,
    UPDATE_PUSH,
    ERROR
}