package com.auction.network;

public enum CommandType {
    LOGIN, REGISTER,
    CANCEL_AUCTION,
    GET_AUCTIONS, GET_AUCTION_DETAIL, GET_MY_BIDS,
    GET_WON_AUCTIONS, GET_BID_HISTORY,
    CREATE_AUCTION, PLACE_BID,
    REGISTER_AUTO_BID, CANCEL_AUTO_BID,
    CLOSE_AUCTION, PAY_AUCTION, UPDATE_AUCTION,
    UPDATE_PUSH,
    // Admin Commands
    GET_ALL_USERS, UPDATE_USER_STATUS, DELETE_USER,
    ADMIN_FORCE_FINISH_AUCTION, GET_ALL_BIDS,
    ERROR
}